### PR TITLE
Dark mode (closes #1378)

### LINKED ISSUE #1378: [Suggestion] Dark Mode ready implementation
I propose add dark mode to the documentation with this code, copy&paste!

See here more:

https://gist.github.com/matiaslopezd/86a7450c92620cb9f4d179677cd279e2

### PR DESCRIPTION
**Pull request by mhillerstrom**
An implementation of the suggestions of @matiaslopezd.

The dark mode CSS can be changed in `theme/layouts/Layout.vue`. Had to implement Font Awesome to get the Lightbulb (and ThumbsUp), but tree-shaking makes this a minor addition.

Hopefully, Dark-Moders will thrive with this addition!

### CODE REVIEW

**Comment by matiaslopezd** [comment]
Excellent!! 👏🏻👏🏻👏🏻

**Comment by daffl** [comment]
Awesome, this is great! From the build error it looks like the following dependencies still need to be added to the `package.json`:

- `@fortawesome/free-solid-svg-icons`
- `@fortawesome/vue-fontawesome`
- `@fortawesome/fontawesome-svg-core`

**Comment by mhillerstrom** [comment]
Strange, because it works perfectly on my machine and ‘npm run netlifly’ compiles both client and server without any problems (it complains about an old browser list…).

 

Can it be due to not including ‘package-lock.json’ in the commit?

 

/Michael

**Comment by mhillerstrom** [comment]
@daffl I omitted `package-lock.json` in my commit - now it passes all gates.

**Comment by daffl** [comment]
Perfect, this is now available at https://docs.feathersjs.com. Thank you very much for the contribution!

**Comment by J3m5** [comment]
Just noticed it, this is awesome!
Thank you @mhillerstrom!

**Pull request merged**
