### PR TITLE
Updated `keep` hook docs to warn about it not having any magic provid…

### PR DESCRIPTION
**Pull request by Mattchewone**
…er checks built in

### CODE REVIEW

**Comment by Mattchewone** [comment]
@eddyystop I just added the warning and a `proTip` example like the `discard` hook. 

Thanks

**Comment by eddyystop** [comment]
Do you think it might better to say this hook will remove any fields not specified even if the service is called on the server. The present wording may sound innocuous to someone reading quickly.

**Comment by Mattchewone** [comment]
@eddyystop Just updated, hopefully that is a little clearer.

**Comment by eddyystop** [comment]
Thanks.

**Pull request merged**
