### PR TITLE
start rewrite of auth management API docs

### PR DESCRIPTION
**Pull request by arve0**
Edited to section with redux. Stopping here and pushing to get feedback.

Issue #883. feathers-plus/feathers-authentication-management#8 might
hold some improvements also (have not read the issue yet).

### CODE REVIEW

**Comment by eddyystop** [comment]
I'm leary of the removal of so much information. The reasoning behind one of the major rewrites of the repo is lost.

**Comment by arve0** [comment]
Thanks for the feedback! The intent of this PR is not *removing* information, but rather *refining* it. Currently, the page is written like a guide, not like an API documentation.

> I'm leary of the removal of so much information.

Do you specifically mean "Multiple communication channels", "Capabilities", "User notifications may be sent for", and "May be used with"? Or is there anything else that is removed?

The reason I ask, is because I've tried to maintain all information, but keep it in one place. E.g. Not repeating information. If this is not the case, I would appreciate concrete comments, I might actually have removed something without intention.

> The reasoning behind one of the major rewrites of the repo is lost.

I'm sorry, but I'm unable to find the reasoning in the git history. Can you help me out with an issue number or some more context?

**Comment by eddyystop** [comment]
I'm impressed you went looking the issue. :) You didn't find it because this code has had different names during its 3 rewrites. https://github.com/eddyystop/feathers-service-verify-reset/issues/18

I think its worthwhile to mention this is the reason the repo supports certain features.

**Comment by eddyystop** [comment]
I agree the docs are an intersection of guide and API, and that it should change.

I'm finalizing a new theme for documentation. I'd be delighted if you wanted to handle the docs for this repo once that is solidified.

**Comment by arve0** [comment]
> I'm finalizing a new theme for documentation. I'd be delighted if you wanted to handle the docs for this repo once that is solidified.

Just bump this thread with instructions, and I'll have a look at it 👍

**Comment by eddyystop** [comment]
Could you ping me at johnsz9999 (at) g mail (dot) com ?

**Pull request closed without merging**
